
import React from 'react';
import { Project, Step } from './types';

interface PluginProps {
  project: Project;
  onSave: (updatedProject: Project) => void;
  theme: 'light' | 'dark';
  onNotify: (msg: string) => void;
}

const JiraManagementConsole: React.FC<PluginProps> = ({ project, onSave, theme, onNotify }) => {
  const steps = project.steps || [];
  const completed = steps.filter(s => s.status === 'completed').length;
  const inProgress = steps.filter(s => s.status === 'in-progress').length;
  const pending = steps.filter(s => s.status === 'pending').length;
  const failed = steps.filter(s => s.status === 'failed').length;

  const handleAddSyncTask = () => {
    const newTask: Step = {
      id: `step_sync_${Date.now()}`,
      title: 'Weekly System Sync',
      category: 'backend',
      status: 'pending',
      content: 'Generated by Jira Management Console. Automated protocol synchronization and log review.',
      createdAt: Date.now()
    };

    onSave({
      ...project,
      steps: [...project.steps, newTask]
    });
    
    onNotify("Added automated sync task to timeline.");
  };

  return (
    <div className="p-8 font-sans h-full bg-[#F4F5F7] dark:bg-[#091E42] text-[#172B4D] dark:text-[#EBECF0] overflow-y-auto custom-scrollbar">
      <div className="max-w-4xl mx-auto">
        <header className="mb-8 border-b border-[#DFE1E6] dark:border-[#253858] pb-6 flex justify-between items-end">
          <div>
            <h1 className="text-2xl font-semibold mb-1">Project Status Report</h1>
            <p className="text-[#5E6C84] dark:text-[#97A0AF] text-sm font-normal">
              Protocol: <span className="font-mono font-bold text-[#0052CC] dark:text-[#4C9AFF]">{project.id}</span>
            </p>
          </div>
          <div className="flex gap-2">
             <button 
               onClick={handleAddSyncTask}
               className="bg-[#0052CC] hover:bg-[#0747A6] text-white px-4 py-2 rounded text-sm font-medium transition-colors shadow-sm"
             >
               Add System Sync
             </button>
          </div>
        </header>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-4 mb-8">
          <StatCard label="Completed" count={completed} color="text-[#36B37E]" bg="bg-[#E3FCEF]" />
          <StatCard label="In Progress" count={inProgress} color="text-[#FFAB00]" bg="bg-[#FFF7E6]" />
          <StatCard label="Pending" count={pending} color="text-[#42526E]" bg="bg-[#F4F5F7]" />
          <StatCard label="Failed" count={failed} color="text-[#BF2600]" bg="bg-[#FFEBE6]" />
        </div>

        <div className="bg-white dark:bg-[#101214] rounded-lg border border-[#DFE1E6] dark:border-[#253858] shadow-sm p-6">
          <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
            <span className="w-2 h-6 bg-[#0052CC] rounded-full"></span>
            Management Insight
          </h2>
          <div className="space-y-4">
            <p className="text-sm leading-relaxed">
              This project currently contains <span className="font-bold">{steps.length}</span> documented protocols. 
              The current velocity suggests a <span className="text-[#36B37E] font-bold">Healthy</span> deployment cycle.
            </p>
            
            <div className="grid grid-cols-2 gap-4 text-xs font-mono">
               <div className="p-3 bg-[#FAFBFC] dark:bg-[#0747A6]/10 rounded border border-[#DFE1E6] dark:border-[#253858]">
                  <span className="block text-[#5E6C84] mb-1">THEME_MODE</span>
                  <span className="uppercase font-bold">{theme}</span>
               </div>
               <div className="p-3 bg-[#FAFBFC] dark:bg-[#0747A6]/10 rounded border border-[#DFE1E6] dark:border-[#253858]">
                  <span className="block text-[#5E6C84] mb-1">PLUGIN_VER</span>
                  <span className="font-bold">v1.1.0_ENTERPRISE</span>
               </div>
            </div>
          </div>
        </div>

        <footer className="mt-12 text-center border-t border-[#DFE1E6] dark:border-[#253858] pt-6">
           <p className="text-[10px] text-[#5E6C84] uppercase tracking-widest font-bold">
             ATLASSIAN DESIGN SYSTEM COMPATIBLE 
           </p>
        </footer>
      </div>
    </div>
  );
};

const StatCard: React.FC<{ label: string, count: number, color: string, bg: string }> = ({ label, count, color, bg }) => (
  <div className={`${bg} dark:bg-black/40 border border-[#DFE1E6] dark:border-[#253858] p-4 rounded-lg`}>
    <span className="block text-[10px] uppercase font-bold text-[#5E6C84] dark:text-[#97A0AF] mb-1">{label}</span>
    <span className={`text-2xl font-bold ${color}`}>{count}</span>
  </div>
);

const plugin = {
  Component: JiraManagementConsole
};

export default plugin;
